### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/agusrabadan-map-practice#2]
# Revisión - Realizar cambios ⚠️
- [ ] Estilo de código y limpieza
# Feedback
## Mejores prácticas/comentarios
- Buena lógica en tu proyecto pero te faltan algunas cosas por implementar. Date cuenta de que hay dos palos de la baraja que son de color rojo y dos que son de color negro. Además de que el palo aparece arriba y abajo (invertido).
![Captura de pantalla de 2024-04-08 13-26-58](https://github.com/4GeeksAcademy/agusrabadan-map-practice/assets/139759297/b19b62f8-9022-40c3-ade0-26cce62afa3c)

Este es el ejemplo de 4Geeks 
![Captura de pantalla de 2024-04-08 13-29-59](https://github.com/4GeeksAcademy/agusrabadan-map-practice/assets/139759297/523bb12d-3273-4f2d-a25c-554afbe02a8c)

**Comment by agusrabadan** [comment]
Ok Edo, ya lo modifiqué, lo saqué sin mirar tu captura jaja ;-) gracias. No me dió tiempo a investigar el tema del temporizador, esta tarde trastearé un rato antes de clase
